spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:h2:mem:mydatabase
    username: vincent
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
